import{loadFirebaseProduct,loadFirebaseCatalog}from'./firebase-store.js?v=8';
const $=q=>document.querySelector(q);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=c=>Number(c||0)<=0?'GRATIS':new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR'}).format(Number(c)/100);
function youtubeId(url){try{const u=new URL(url);if(u.hostname.includes('youtu.be'))return u.pathname.slice(1).split('/')[0];if(u.hostname.includes('youtube.com')){if(u.pathname.startsWith('/shorts/'))return u.pathname.split('/')[2];return u.searchParams.get('v')}}catch{}return null}
function card(p){const d=document.createElement('a');d.className='product-card';d.href=`./resource.html?id=${encodeURIComponent(p.id)}`;d.style.textDecoration='none';d.style.color='inherit';d.innerHTML=`<div class="card-media">${p.image_url?`<img src="${esc(p.image_url)}" alt="">`:`<div class="fallback"><b>DEMON</b></div>`}<div class="badge ${Number(p.price_cents||0)<=0?'free':''}">${Number(p.price_cents||0)<=0?'FREE':'PREMIUM'}</div></div><div class="card-body"><div class="category-pill">${esc(p.category_name||p.category||'Scripts')}</div><h3>${esc(p.title||p.name||'Resource')}</h3><p>${esc(p.description||'')}</p><div class="card-foot"><div class="price ${Number(p.price_cents||0)<=0?'free':''}">${money(p.price_cents)}</div></div></div>`;return d}
async function init(){
 const id=new URLSearchParams(location.search).get('id');if(!id){$('#resourceLoading').innerHTML='<h3>Risorsa non specificata</h3>';return}
 const p=await loadFirebaseProduct(id);if(!p){$('#resourceLoading').innerHTML='<h3>Risorsa non trovata</h3>';return}
 document.title=`${p.title||p.name} • Demon Leaks`;$('#resourceLoading').classList.add('hidden');$('#resourceApp').classList.remove('hidden');
 $('#crumbCategory').textContent=p.category_name||p.category||'Scripts';$('#crumbTitle').textContent=p.title||p.name;$('#resourceCategory').textContent=p.category_name||p.category||'Scripts';$('#resourceTitle').textContent=p.title||p.name||'Demon Resource';$('#resourceDescription').textContent=p.description||'';$('#resourceCover').src=p.image_url||'./assets/demon-banner.png';$('#resourceCover').onerror=()=>$('#resourceCover').src='./assets/demon-banner.png';
 const price=Number(p.price_cents||0);$('#resourcePrice').textContent=money(price);$('#resourceType').textContent=price<=0?'FREE':'PREMIUM';$('#resourceVersion').textContent=p.version||'—';$('#resourceAuthor').textContent=p.author||'Demon Leaks';$('#resourceUpdated').textContent=String(p.updated_at||p.created_at||'—').slice(0,10);$('#resourceFavorite').dataset.favoriteId=p.id;
 const action=$('#resourceMainAction');if(price<=0){action.textContent='Scarica protetto';action.dataset.demonDownload=p.id}else{action.textContent='Vai al pagamento';action.onclick=()=>{localStorage.setItem('demon_cart',JSON.stringify([{id:p.id,title:p.title||p.name,price_cents:price,image_url:p.image_url||''}]));localStorage.setItem('demon_open_cart','1');location.href='./#catalog'}}
 const gallery=[p.image_url,...(Array.isArray(p.gallery_urls)?p.gallery_urls:[])].filter(Boolean);$('#resourceGallery').innerHTML='';[...new Set(gallery)].slice(0,8).forEach(url=>{const b=document.createElement('button');b.innerHTML=`<img src="${esc(url)}" alt="">`;b.onclick=()=>$('#resourceCover').src=url;$('#resourceGallery').appendChild(b)});
 const vids=(Array.isArray(p.youtube_urls)?p.youtube_urls:[]).map(youtubeId).filter(Boolean);if(vids.length){$('#videoPanel').classList.remove('hidden');$('#youtubeGrid').innerHTML=vids.map(v=>`<iframe class="youtube-frame" src="https://www.youtube-nocookie.com/embed/${encodeURIComponent(v)}" title="YouTube video" allowfullscreen loading="lazy"></iframe>`).join('')}
 const tags=Array.isArray(p.tags)?p.tags:[];if(tags.length){$('#tagsPanel').classList.remove('hidden');$('#tagsList').innerHTML=tags.map(t=>`<span class="tag">${esc(t)}</span>`).join('')}
 const all=await loadFirebaseCatalog()||[];all.filter(x=>x.id!==p.id&&(x.category_slug===p.category_slug||x.category===p.category)).slice(0,4).forEach(x=>$('#relatedGrid').appendChild(card(x)));
}
init().catch(e=>{console.error(e);$('#resourceLoading').innerHTML='<h3>Errore nel caricamento</h3>'});